import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Navbar } from '@/components/shared/Navbar';
import { getMe } from '@/service/getMe';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
    title: 'RentNest',
    description: 'Generated by RentNest',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await getMe();

    return (
        <html
            lang="en"
            className={cn('h-full', 'antialiased', 'font-sans', inter.variable)}
        >
            <body className="min-h-full flex flex-col">
                <Navbar user={user} />
                {children}
                <Toaster richColors position="top-right" />
            </body>
        </html>
    );
}
